services:


  # MySQL database service
  db:
    image: mysql:8.3.0
    container_name: mysql-db # Lowercase and underscores (naming convention)
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root  # Set a strong password for the MySQL root user
    volumes:
      - ./mysql-data/data:/var/lib/mysql # Persist data volume for database
      - ./mysql-init/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql  # Mount SQL files for initialization
    networks:
      - mysql-compose-network
      
      
  # phpMyAdmin service (management UI)
  phpmyadmin:
    image: phpmyadmin 
    container_name: pma-ui
    restart: always
    ports:
      - "8081:80"  # Maps port 8081 on your host to port 80 (default for phpMyAdmin) inside the container
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db  # This ensures the database service is started before phpMyAdmin attempts to connect
    networks:
      - mysql-compose-network
      
networks:
  mysql-compose-network: 